blank_issues_enabled: false
contact_links:
  - name: Security Vulnerabilities
    url: https://github.com/fabiograsso/okta-opaflix/security/advisories/new
    about: Report security vulnerabilities privately
